# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: bionic # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  global:
    - ROS_DISTRO=noetic
    - ROS_REPO=ros
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter"
    - WARNINGS_OK=false
  matrix:
    - TEST="clang-format, catkin_lint"
    - TEST=code-coverage
    - ROS_DISTRO=melodic

matrix:
  include:
    - compiler: clang
      env: TEST=clang-tidy-fix

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
